### ISSUE TITLE
Consider making this into an offline-first, installable PWA

### ISSUE THREAD

**Issue by Jaifroid** [btheado/tiddlystow#11]
This project would be perfect as an offline-enabled, installable Progressive Web App. This would be better in many ways than using the tiddlywiki desktop app (because much smaller and more agile, might even run on mobile Chromium, at least on Android). The user would only need to visit the GitHub page once, install the PWA, and the app would cache its own code, so that it can be used without requiring access to the server. It would still access the server when online (on startup) to check for updates, so the PWA can be kept automatically up-to-date.

**Comment by btheado** [comment]
Thanks @Jaifroid. Seems like a good idea to me and it shouldn't be very difficult to implement. Probably testing is the hardest part. I'll consider looking into it.

**Comment by Jaifroid** [comment]
@btheado It's great you're working on this. Just to say that to make a PWA fully offline-enabled, it needs to cache its own code. All Service Workers also need to claim the client(s) that they are going to control if it's desired that they start controlling the browser's Fetch requests straight away.

See Mozilla's full offline example here:

https://github.com/mdn/dom-examples/blob/main/service-worker/simple-service-worker/sw.js

And the friendly explanations here: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#registering_your_worker

**Comment by btheado** [comment]
Thanks for the links. The code I wrote does cached its own code. My first attempt I accidentally had some absolute paths and didn't notice because locally I was testing with it at a root url. I fixed that issue now.

If you still see something wrong, please let me know how to reproduce the issue.

**Comment by Jaifroid** [comment]
Oh I see, I just looked at the commit that closed the issue, and so got a bit confused. Great!

**Comment by btheado** [comment]
I should have made the commits into a PR so they could all be tagged to this issue. For future reference, these are the related commits:

https://github.com/btheado/tiddlystow/compare/d377a5e2d...4b8d2ac9

**Comment by Jaifroid** [comment]
Ha ha, I sometimes do that too when I think a change will be small, but it ends up being several commits!

I look forward to trying it out, and will report back any issues.

**Comment by Jaifroid** [comment]
@btheado I've tested it in Edge (Chromium), and was able to install it from the address bar. Then I exited, put my machine in offline mode, opened the install app, and all worked perfectly for editing and saving. Congratulations!

**Comment by btheado** [comment]
Great. Thanks for the confirmation!
